version: '3'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth_server
      - notes_server

  auth_server:
    build:
      context: ./auth_server
      dockerfile: Dockerfile

  notes_server:
    build:
      context: ./notes_server
      dockerfile: Dockerfile
