version: '3'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth_srv
      - notes_srv

  auth_srv:
    build:
      context: ./autenticacion
      dockerfile: Dockerfile

  notes_srv:
    build:
      context: ./notas
      dockerfile: Dockerfile
