version: '3.8'

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - notes_service

  auth_service:
    build: ./auth_service
    ports:
      - "5000"

  notes_service:
    build: ./notes_service
    ports:
      - "5000"
